### ISSUE TITLE
Текст пояснения и графики не совпадают в 10 главе

### ISSUE THREAD

**Issue by Dmitryi** [locusclassicus/text_analysis_2024#1]
https://locusclassicus.github.io/text_analysis_2024/count.html
В 10 главе внизу вы пишите

"Слова, расположенные ближе к линии, примерно одинаково представлены в обоих текстах (например, “ум” и “душа” у Беркли и Локка); слова, которые находятся дальше от линии, более свойственны одному из двух авторов: например, у Беркли чаще встречается “абстрактный” по сравнению с первой книгой Локка, а у Локка чаще используется слово “простой”."

Но анализиуруете тексты Юма и Локка

```
long_freq <- spread_freq |> 
  pivot_longer(c("Hume", "Locke"), names_to = "author", values_to = "tf")
```

**Comment by locusclassicus** [comment]
Частотности для Юма и Лока упаковываются в один столбец (ось х), оба сравниваются с Беркли (ось y), так что там все верно.

**Comment by Dmitryi** [comment]
> Частотности для Юма и Лока упаковываются в один столбец (ось х), оба сравниваются с Беркли (ось y), так что там все верно.

Хорошо. Теперь понятно!
На мой взгляд в тексте это нужно обозначить иначе контекст совершенно не очевиден.

**Comment by locusclassicus** [comment]
Справедливое замечание, спасибо, учту при доработке курса.
