### ISSUE TITLE
Оглавление (слева) не во всех главах отображается полностью

### ISSUE THREAD

**Issue by Dmitryi** [locusclassicus/text_analysis_2024#2]
В 12 главе оглавление (слева) отображает не полный список глав.
![Screenshot 2024-11-24 at 16-52-59 Компьютерный анализ текста - 12 Латентно-семантический анализ](https://github.com/user-attachments/assets/f07e8d8c-8f99-4463-b41a-abf544965500)

**Comment by locusclassicus** [comment]
@Dmitryi Спасибо, баг иногда вылезает, потому что новые главы добавляются быстрее, чем обновляются старые. Поправила
